(() => {"use strict";
const KEY="rikaLab6.body.v1",esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fresh=()=>({layer:0,model:false,trace:"oxygen",activity:0,breath:0,food:0,time:0,records:[],evidence:[]});
function mount(root){let s=fresh(),run=false,raf=0;try{s={...s,...JSON.parse(localStorage.getItem(KEY))};}catch(_){}
root.innerHTML=`<nav class="breadcrumbs"><button class="text-button" data-lab-home type="button">LAB一覧</button><span>›</span><span>からだLAB</span></nav><section class="body-lab"><header class="lab-titlebar"><div><p class="eyebrow">人や動物の体</p><h1>🫀 からだLAB</h1><p>空気・食べ物・血液を追い、臓器がつながって働く様子を調べよう。</p></div><div class="body-status" data-status></div></header><div class="body-workspace"><section class="body-stage-wrap"><svg class="body-svg" viewBox="0 0 760 590" data-svg></svg><div class="body-tip">色や点は、体の中の変化を考えるためのモデルです。</div></section><aside class="body-panel" data-panel></aside></div><section class="body-bottom"><div class="body-record"><h2>証拠カード</h2><label>予想<textarea data-prediction placeholder="どうなると思う？"></textarea></label><label>考察<textarea data-thought placeholder="見えたことと考えたこと"></textarea></label><button class="primary-button" data-record type="button">この観察を保存</button><button class="secondary-button" data-clear type="button">結果をリセット</button></div><div class="body-data"><h2>比較データ</h2><div data-data></div></div></section><p class="model-note">臓器・血液・酸素・養分の表示は、見えない体内の関係を考えるために簡略化したモデルです。血液そのものが青色になるわけではありません。</p></section>`;
const svg=root.querySelector('[data-svg]'),panel=root.querySelector('[data-panel]');
function draw(){const heart=72+s.activity*28,breath=15+s.activity*7,co2=3+s.breath*.04,oxy=21-s.breath*.03,food=Math.min(100,s.food+s.time*3),stage=s.trace==='food'?(food>70?'胃・消化管':food>25?'小腸・吸収':'口・食道'):s.trace==='blood'?(s.time%4<1?'肺付近':s.time%4<2?'心臓':'全身'):s.trace==='co2'?'肺へ戻る':'肺→血液→全身';
let organs=s.layer?`<g class="organs"><ellipse cx="310" cy="150" rx="58" ry="76" class="lung"/><ellipse cx="450" cy="150" rx="58" ry="76" class="lung"/><path d="M380 185q-45 55 0 92q45-37 0-92" class="heart-shape"/><path d="M380 230q-30 42-16 92h32q14-50-16-92M380 322q-40 40-10 115h20q30-75-10-115" class="digest"/><ellipse cx="330" cy="320" rx="35" ry="18" class="organ-small"/><ellipse cx="430" cy="395" rx="18" ry="42" class="organ-small"/><ellipse cx="350" cy="395" rx="18" ry="42" class="organ-small"/><text x="275" y="70" class="body-label">肺</text><text x="395" y="200" class="body-label">心臓</text><text x="290" y="365" class="body-label">小腸</text>`:"";
let dots=s.model?Array.from({length:16},(_,i)=>`<circle class="body-dot" cx="${350+(i*47)%90}" cy="${140+(i*31)%245}" r="5" style="--delay:${i*.1}s"/>`).join(""):"";
svg.innerHTML=`<rect width="760" height="590" fill="#f6f0f1"/><text x="28" y="38" class="body-board-title">BODY EXPLORER</text><circle cx="380" cy="92" r="34" class="skin"/><path d="M380 127q-76 22-80 118l35 12 8 205M380 127q76 22 80 118l-35 12-8 205M343 250l-58 150M417 250l58 150M343 250l37 22 37-22" class="body-outline"/>${organs}${dots}${s.model?`<path class="blood-path" d="M380 185Q270 110 310 150M450 150Q520 260 420 250M420 250Q530 350 460 430"/>`:''}<text x="380" y="535" text-anchor="middle" class="body-caption">現在地：${esc(stage)}　時間 ${Math.round(s.time)}</text>`;
panel.innerHTML=`<h2>観察する</h2><p>見たい流れを選び、時間を進めてみよう。</p><div class="body-modes"><button data-layer>${s.layer?'主な臓器を隠す':'からだの中を見る'}</button><button data-model>${s.model?'モデルを隠す':'モデルを見る'}</button><button data-breath>息を ${s.breath%2?'はく':'吸う'}</button></div><h3>追跡するもの</h3><div class="body-trace"><button data-trace="oxygen" aria-pressed="${s.trace==='oxygen'}">酸素</button><button data-trace="blood" aria-pressed="${s.trace==='blood'}">血液</button><button data-trace="food" aria-pressed="${s.trace==='food'}">食べ物・養分</button><button data-trace="co2" aria-pressed="${s.trace==='co2'}">二酸化炭素</button></div><h3>条件</h3><label class="body-range">運動 <output>${['安静','軽い運動','強い運動'][s.activity]}</output><input data-activity type="range" min="0" max="2" value="${s.activity}"></label><div class="body-actions"><button data-eat>🍙 食べる</button><button data-step>▶ ×1</button><button data-fast>▶▶ ×10</button><button data-run>${run?'⏸ 止める':'▶ 自動で進める'}</button><button data-reset>リセット</button></div><div class="body-readout"><b>観察できる値</b><span>呼吸 ${breath}回相当　心臓 ${heart}回相当</span><small>吸う空気 酸素 ${oxy.toFixed(1)}　はく空気 二酸化炭素 ${co2.toFixed(1)}</small><small>今いる場所：${esc(stage)}</small></div>`;
root.querySelector('[data-status]').textContent=`${['安静','軽い運動','強い運動'][s.activity]}・${s.trace==='food'?'消化と吸収':s.trace==='blood'?'血液循環':'呼吸の観察'}`;bind();
}
function bind(){panel.querySelector('[data-layer]').onclick=()=>{s.layer=s.layer?0:1;draw();};panel.querySelector('[data-model]').onclick=()=>{s.model=!s.model;draw();};panel.querySelector('[data-breath]').onclick=()=>{s.breath++;draw();};panel.querySelector('[data-eat]').onclick=()=>{s.food=100;s.trace='food';draw();};panel.querySelectorAll('[data-trace]').forEach(b=>b.onclick=()=>{s.trace=b.dataset.trace;draw();});panel.querySelector('[data-activity]').oninput=e=>{s.activity=+e.target.value;draw();};panel.querySelector('[data-step]').onclick=()=>{s.time++;draw();};panel.querySelector('[data-fast]').onclick=()=>{s.time+=10;draw();};panel.querySelector('[data-run]').onclick=()=>{run=!run;if(run)loop();draw();};panel.querySelector('[data-reset]').onclick=()=>{s={...fresh(),records:s.records,evidence:s.evidence};run=false;draw();};}
function loop(){if(!run)return;s.time+=.15;draw();raf=requestAnimationFrame(loop);}
root.querySelector('[data-record]').onclick=()=>{const e=`${s.trace}を追跡：現在地 ${s.trace==='food'?'小腸・吸収':s.trace==='blood'?'全身':'肺・血液'}／運動 ${s.activity}`;s.evidence.unshift(e);s.records.unshift({e,prediction:root.querySelector('[data-prediction]').value,thought:root.querySelector('[data-thought]').value});try{localStorage.setItem(KEY,JSON.stringify(s));}catch(_){}draw();};root.querySelector('[data-clear]').onclick=()=>{s.evidence=[];s.records=[];try{localStorage.removeItem(KEY);}catch(_){}draw();};draw();return()=>{run=false;cancelAnimationFrame(raf);};}
window.RikaLabSimulations=window.RikaLabSimulations||{};window.RikaLabSimulations.body={mount};})();
