(() => {"use strict";
const KEY="rikaLab6.earth.v1",esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fresh=()=>({view:"surface",water:65,speed:55,sediment:55,volcano:0,quake:0,time:0,layers:["れき","砂","泥"],samples:[],evidence:[],events:[],records:[]});
function mount(root){let s=fresh(),run=false,raf=0;try{s={...s,...JSON.parse(localStorage.getItem(KEY))};}catch(_){}
root.innerHTML=`<nav class="breadcrumbs"><button class="text-button" data-lab-home type="button">LAB一覧</button><span>›</span><span>大地LAB</span></nav><section class="earth-lab"><header class="lab-titlebar"><div><p class="eyebrow">土地のつくりと変化</p><h1>🌋 大地LAB</h1><p>地層に残された証拠を調べ、自分で地層をつくり、過去の大地を考えよう。</p></div><div class="earth-status" data-status></div></header><div class="earth-workspace"><section class="earth-stage-wrap"><svg class="earth-svg" viewBox="0 0 820 570" data-svg></svg><div class="earth-tip">地表・断面・堆積の変化を切り替え、観察したことを証拠として残せます。</div></section><aside class="earth-panel" data-panel></aside></div><section class="earth-bottom"><div class="earth-record"><h2>証拠と推理</h2><label>予想<textarea data-prediction placeholder="この土地はどうやってできたと思う？"></textarea></label><label>推理・考察<textarea data-thought placeholder="証拠から考えたことを書こう"></textarea></label><button class="primary-button" data-record type="button">証拠カードに保存</button><button class="secondary-button" data-clear type="button">結果をリセット</button></div><div class="earth-data"><h2>調査履歴</h2><div data-data></div></div></section><p class="model-note">地層の色・粒・動きは、実際の大地を学習用に単純化したモデルです。地層の順番や変化は、条件によって異なります。</p></section>`;
const svg=root.querySelector('[data-svg]'),panel=root.querySelector('[data-panel]');
function addLayer(){const m=s.speed>70?"泥":s.speed>40?"砂":"れき";s.layers.push(m);s.events.unshift(`堆積：${m}`);s.time++;}
function draw(){const h=s.layers.length,labels=s.layers.map((m,i)=>`<g class="earth-layer"><rect x="130" y="${395-i*38}" width="560" height="35" fill="${m==='れき'?'#b19a7d':m==='砂'?'#d7bd89':'#9b8d83'}"/><text x="150" y="${419-i*38}" class="layer-label">${m}</text><text x="655" y="${419-i*38}" class="layer-event">層 ${i+1}</text></g>`).join('');const shift=s.quake?28:0;svg.innerHTML=`<rect width="820" height="570" fill="#e9f2f7"/><rect y="390" width="820" height="180" fill="#b4926d"/><path d="M0 390Q160 330 300 380T560 350T820 385V0H0Z" fill="#81b56a"/><path d="M0 372Q120 350 240 372T480 365T820 360" fill="none" stroke="#4c9ca8" stroke-width="9" opacity=".8"/><path d="M580 360Q600 270 665 220" stroke="#6f5747" stroke-width="35" fill="none"/><path d="M600 205q-10-32 25-70q38 35 30 70" fill="#b65e45" opacity="${s.volcano?1:.25}"/>${s.view==='section'?`<g transform="translate(${shift} 0)">${labels}${s.volcano?`<rect x="130" y="${395-h*38}" width="560" height="25" fill="#655e63"/><text x="150" y="${413-h*38}" class="layer-label">火山灰</text>`:''}</g>`:`<text x="410" y="455" text-anchor="middle" class="earth-caption">地表を観察しています。断面を開いて地下を調べよう。</text>`}${s.quake?`<path d="M425 390l-22 180" stroke="#80534d" stroke-width="6" stroke-dasharray="8 8"/>`:''}<text x="30" y="38" class="earth-title">EARTH FIELD</text><text x="410" y="535" text-anchor="middle" class="earth-caption">時間 ${Math.round(s.time)}　水の速さ ${s.speed}　時間スケール：${s.time<10?'実験モデル':s.time<100?'数年':'長い年月'}</text>`;
panel.innerHTML=`<h2>調査と実験</h2><p>地表を調べ、断面を見て、地層のでき方を試そう。</p><div class="earth-tabs"><button data-view="surface" aria-pressed="${s.view==='surface'}">地表を見る</button><button data-view="section" aria-pressed="${s.view==='section'}">断面を見る</button></div><div class="earth-actions"><button data-sample>⛏ サンプル採取</button><button data-bore>柱状図を調べる</button><button data-flow>💧 水を流す</button><button data-volcano>🌋 火山灰を重ねる</button><button data-quake>地震前後を比べる</button><button data-replay>⏪ でき方を見る</button></div><h3>堆積条件</h3><label class="earth-range">水の速さ <output>${s.speed}</output><input data-k="speed" type="range" min="10" max="100" value="${s.speed}"></label><label class="earth-range">土砂の量 <output>${s.sediment}</output><input data-k="sediment" type="range" min="10" max="100" value="${s.sediment}"></label><div class="earth-time"><button data-step>▶ ×1</button><button data-fast>▶▶ ×10</button><button data-run>${run?'⏸ 止める':'▶ 自動で進める'}</button><button data-reset>リセット</button></div><div class="earth-readout"><b>${s.view==='section'?'観察できること':'地表の観察'}</b><span>${s.view==='section'?'層が重なり、粒の種類を比べられます。':'地面の下にはどんな層があるだろう？'}</span><small>調査地点：${s.samples.length?`採取 ${s.samples.length}件`:'未調査'}</small></div>`;root.querySelector('[data-status]').textContent=`${s.view==='section'?'断面観察':'地表観察'}・証拠 ${s.evidence.length}件`;bind();}
function bind(){panel.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{s.view=b.dataset.view;draw();});panel.querySelector('[data-sample]').onclick=()=>{s.samples.unshift(`地点A・深さ${s.layers.length}`);s.evidence.unshift('地層サンプルを採取した');draw();};panel.querySelector('[data-bore]').onclick=()=>{s.view='section';s.evidence.unshift(`柱状図：${s.layers.join(' → ')}`);draw();};panel.querySelector('[data-flow]').onclick=()=>{for(let i=0;i<3;i++)addLayer();draw();};panel.querySelector('[data-volcano]').onclick=()=>{s.volcano=1;s.layers.push('火山灰');s.events.unshift('火山灰の堆積');s.time+=10;draw();};panel.querySelector('[data-quake]').onclick=()=>{s.quake=s.quake?0:1;s.events.unshift(s.quake?'地震：地層がずれた':'地震前に戻した');draw();};panel.querySelector('[data-replay]').onclick=()=>{s.time=Math.max(0,s.time-10);s.layers=s.layers.slice(0,Math.max(3,s.layers.length-1));draw();};panel.querySelectorAll('input').forEach(x=>x.oninput=()=>{s[x.dataset.k]=+x.value;draw();});panel.querySelector('[data-step]').onclick=()=>{addLayer();draw();};panel.querySelector('[data-fast]').onclick=()=>{for(let i=0;i<10;i++)addLayer();draw();};panel.querySelector('[data-run]').onclick=()=>{run=!run;if(run)loop();draw();};panel.querySelector('[data-reset]').onclick=()=>{s={...fresh(),records:s.records,evidence:s.evidence};run=false;draw();};}
function loop(){if(!run)return;addLayer();draw();raf=requestAnimationFrame(loop);}
root.querySelector('[data-record]').onclick=()=>{const e=`観察：${s.view==='section'?'地層の重なり':'地表'}／証拠：${s.evidence[0]||'未選択'}／イベント：${s.events[0]||'なし'}`;s.evidence.unshift(e);s.records.unshift({e,prediction:root.querySelector('[data-prediction]').value,thought:root.querySelector('[data-thought]').value});try{localStorage.setItem(KEY,JSON.stringify(s));}catch(_){}draw();};root.querySelector('[data-clear]').onclick=()=>{s.evidence=[];s.records=[];try{localStorage.removeItem(KEY);}catch(_){}draw();};draw();return()=>{run=false;cancelAnimationFrame(raf);};}
window.RikaLabSimulations=window.RikaLabSimulations||{};window.RikaLabSimulations.earth={mount};})();
