(() => {"use strict";
const KEY="rikaLab6.environment.v1",esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fresh=()=>({plant:52,insect:18,small:10,bird:6,water:75,green:80,air:50,time:0,trace:"insect",foodView:false,waterView:false,airView:false,records:[],evidence:[]});
function mount(root){let s=fresh(),run=false,raf=0;try{s={...s,...JSON.parse(localStorage.getItem(KEY))};}catch(_){}
root.innerHTML=`<nav class="breadcrumbs"><button class="text-button" data-lab-home type="button">LAB一覧</button><span>›</span><span>生物と環境LAB</span></nav><section class="environment-lab"><header class="lab-titlebar"><div><p class="eyebrow">生物と環境</p><h1>🕸️ 生物と環境LAB</h1><p>草地の一つの条件を変え、時間を進めて、つながった変化を見つけよう。</p></div><div class="environment-status" data-status></div></header><div class="environment-workspace"><section class="environment-stage-wrap"><svg class="environment-svg" viewBox="0 0 800 560" data-svg></svg><div class="environment-tip">自然の関係を分かりやすくしたモデルです。実際の自然には、もっと多くの生物や条件があります。</div></section><aside class="environment-panel" data-panel></aside></div><section class="environment-bottom"><div class="environment-record"><h2>証拠カード</h2><label>予想<textarea data-prediction placeholder="昆虫を増やすと、何が変わると思う？"></textarea></label><label>考察<textarea data-thought placeholder="グラフや自然の変化から考えたこと"></textarea></label><button class="primary-button" data-record type="button">この実験を記録</button><button class="secondary-button" data-clear type="button">結果をリセット</button></div><div class="environment-data"><h2>個体数の変化</h2><div data-graph></div><div data-map></div></div></section></section>`;
const svg=root.querySelector('[data-svg]'),panel=root.querySelector('[data-panel]');
function evolve(){const p=s.plant,i=s.insect,a=s.small,b=s.bird,w=s.water,g=s.green; s.plant=Math.max(2,Math.min(95,p+.025*p*(1-p/100)*g/70-.018*i));s.insect=Math.max(1,Math.min(80,i+.055*i*(p/55)*w/75-.035*a-.02*b));s.small=Math.max(1,Math.min(45,a+.035*a*(i/20)-.028*b-.01*(100-w)));s.bird=Math.max(1,Math.min(30,b+.025*b*(a/12)-.012*b));s.water=Math.max(10,Math.min(100,w-.006*(i+a)+.02*(100-w)));}
function draw(){const pop=[s.plant,s.insect,s.small,s.bird],max=Math.max(20,...pop),trace=s.trace==='plant'?'植物':s.trace==='insect'?'昆虫':s.trace==='small'?'小動物':'鳥';const dots=[['plant','🌱',s.plant,110,370],['insect','🐛',s.insect,270,300],['small','🐸',s.small,440,245],['bird','🐦',s.bird,620,165]];svg.innerHTML=`<rect width="800" height="560" fill="#eaf3e5"/><path d="M0 430Q180 385 360 425T800 405V560H0Z" fill="#7fba69"/><ellipse cx="610" cy="465" rx="150" ry="48" fill="#75b8c5" opacity="${s.water/160+.2}"/><path d="M55 395Q170 320 300 390T550 350T760 380" fill="none" stroke="#6a9f57" stroke-width="8" opacity="${s.green/100}"/>${dots.map(d=>{const n=Math.round(d[2]/(d[0]==='plant'?5:2)),arr=Array.from({length:Math.min(22,n)},(_,i)=>`<text class="eco-creature" x="${d[3]+(i*31)%110}" y="${d[4]+Math.floor(i/4)*26}">${d[1]}</text>`);return arr.join('');}).join('')}<text x="30" y="40" class="eco-title">ECOSYSTEM STAGE</text>${s.foodView?`<path class="relation-food" d="M155 365Q220 310 300 330M330 290Q390 240 465 270M500 235Q560 185 650 190"/>`:''}${s.waterView?`<path class="relation-water" d="M610 430Q470 380 180 385"/>`:''}${s.airView?`<path class="relation-air" d="M120 150Q360 70 680 130"/>`:''}<text x="400" y="530" text-anchor="middle" class="eco-caption">追跡：${trace}　時間 ${Math.round(s.time)}　水 ${Math.round(s.water)}　緑地 ${Math.round(s.green)}</text>`;
panel.innerHTML=`<h2>環境を動かす</h2><p>1つだけ条件を変えて、少しずつ時間を進めよう。</p><h3>生物の数</h3><div class="eco-ranges"><label>🌱 植物 <output>${Math.round(s.plant)}</output><input data-k="plant" type="range" min="5" max="95" value="${s.plant}"></label><label>🐛 昆虫 <output>${Math.round(s.insect)}</output><input data-k="insect" type="range" min="1" max="70" value="${s.insect}"></label><label>🐸 小動物 <output>${Math.round(s.small)}</output><input data-k="small" type="range" min="1" max="40" value="${s.small}"></label><label>🐦 鳥 <output>${Math.round(s.bird)}</output><input data-k="bird" type="range" min="1" max="25" value="${s.bird}"></label></div><h3>環境条件</h3><label class="eco-range">💧 水 <output>${Math.round(s.water)}</output><input data-k="water" type="range" min="10" max="100" value="${s.water}"></label><label class="eco-range">🏞 緑地 <output>${Math.round(s.green)}</output><input data-k="green" type="range" min="10" max="100" value="${s.green}"></label><div class="eco-buttons"><button data-food>🍴 食べ物の関係</button><button data-water>💧 水との関係</button><button data-air>💨 空気を見る</button><button data-trace="insect">昆虫を追う</button></div><div class="eco-time"><button data-step>▶ ×1</button><button data-fast>▶▶ ×10</button><button data-run>${run?'⏸ 止める':'▶ 自動で進める'}</button><button data-reset>リセット</button></div><div class="eco-readout"><b>観察</b><span>追跡中：${trace}</span><small>時間差をつけて変化が広がります。正解の個体数はありません。</small></div>`;root.querySelector('[data-status]').textContent=`${trace}を追跡中・時間 ${Math.round(s.time)}`;root.querySelector('[data-graph]').innerHTML=`<div class="eco-graph">${pop.map((v,i)=>`<div><span>${['植物','昆虫','小動物','鳥'][i]}</span><i style="width:${Math.round(v/max*100)}%"></i></div>`).join('')}</div>`;root.querySelector('[data-map]').innerHTML=`<div class="eco-map">${s.foodView?'🌱 → 🐛 → 🐸 → 🐦　食べ物':''}${s.waterView?'💧 → 🌱・🐸　水':''}${s.airView?'💨 ↔ 🌱・🐛　空気':''}</div>`;bind();}
function bind(){panel.querySelectorAll('input').forEach(x=>x.oninput=()=>{s[x.dataset.k]=+x.value;draw();});panel.querySelector('[data-food]').onclick=()=>{s.foodView=!s.foodView;draw();};panel.querySelector('[data-water]').onclick=()=>{s.waterView=!s.waterView;draw();};panel.querySelector('[data-air]').onclick=()=>{s.airView=!s.airView;draw();};panel.querySelector('[data-step]').onclick=()=>{s.time++;evolve();draw();};panel.querySelector('[data-fast]').onclick=()=>{for(let i=0;i<10;i++){s.time++;evolve();}draw();};panel.querySelector('[data-run]').onclick=()=>{run=!run;if(run)loop();draw();};panel.querySelector('[data-reset]').onclick=()=>{s={...fresh(),records:s.records,evidence:s.evidence};run=false;draw();};}
function loop(){if(!run)return;s.time+=.15;evolve();draw();raf=requestAnimationFrame(loop);}
root.querySelector('[data-record]').onclick=()=>{const e=`時間${Math.round(s.time)}：植物${Math.round(s.plant)}・昆虫${Math.round(s.insect)}・小動物${Math.round(s.small)}・鳥${Math.round(s.bird)}・水${Math.round(s.water)}`;s.evidence.unshift(e);s.records.unshift({e,prediction:root.querySelector('[data-prediction]').value,thought:root.querySelector('[data-thought]').value});try{localStorage.setItem(KEY,JSON.stringify(s));}catch(_){}draw();};root.querySelector('[data-clear]').onclick=()=>{s.evidence=[];s.records=[];try{localStorage.removeItem(KEY);}catch(_){}draw();};draw();return()=>{run=false;cancelAnimationFrame(raf);};}
window.RikaLabSimulations=window.RikaLabSimulations||{};window.RikaLabSimulations.environment={mount};})();
