(() => {
  "use strict";
  window.RikaLabSimulations = window.RikaLabSimulations || {};
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const CONFIG={
    burning:{title:"炎の強さ",hint:"酸素が減ると、炎はどうなる？",controls:[['酸素量',5,21,1,21,'%']],draw:s=>`<div class="extra-fire" style="--fire:${s[0]*4}px">🔥</div><div class="extra-meter"><b>酸素 ${s[0]}%</b><span style="width:${s[0]/21*100}%"></span></div><p>${s[0]<8?'炎は消えました。':'炎は燃えています。'}</p>`},
    solutions:{title:"水溶液の性質",hint:"指示薬の色と蒸発後のようすを比べよう。",controls:[['水溶液',0,2,1,0,''],['指示薬',0,1,1,0,'']],draw:s=>{const names=['食塩水','うすい塩酸','石灰水'], colors=['#d9c34a','#e88787','#8d79d8']; const c=s[1]?(s[0]===0?'#6d8bd8':s[0]===1?'#ed5a68':'#6f45be'):colors[s[0]];return `<div class="solution-beaker"><div style="background:${c}"></div></div><b>${names[s[0]]}</b><p>${s[1]?'指示薬で性質が見えました。':'指示薬を入れてみよう。'}</p>`}},
    electricity:{title:"電気の変換",hint:"光を強くすると、モーターはどうなる？",controls:[['光の強さ',0,100,1,60,'%'],['使うもの',0,1,1,0,'']],draw:s=>`<div class="extra-device">${s[1]?'⚙️':'💡'}</div><div class="energy-flow" style="--flow:${s[0]/2+8}px">⚡ ─────────▶ ${s[1]?'運動':'光'}</div><p>電気の大きさ：${Math.round(s[0]*0.8)}　${s[1]?'回転しています。':'明るさが変わります。'}</p>`},
    plants:{title:"植物の水の通り道",hint:"葉が多いと、水の移動はどうなる？",controls:[['光',0,100,1,70,'%'],['葉の量',0,5,1,3,'枚']],draw:s=>`<div class="plant-model">🌱<span style="height:${35+s[0]/3}px">│</span></div><div class="water-flow">💧 ↑ ↑ ↑ ${Math.round(s[0]*s[1]/5)}%</div><p>葉から出ていく水：${Math.round(s[0]*s[1]/5)}　（モデル値）</p>`},
    body:{title:"運動とからだ",hint:"運動すると、心拍と呼吸はどう変わる？",controls:[['運動量',0,5,1,1,'段階']],draw:s=>`<div class="body-model">🫀 <span class="pulse" style="--pulse:${Math.max(0.25,1-s[0]/10)}s">♥</span> 🫁</div><div class="vital-grid"><b>心拍 ${70+s[0]*18} 回/分</b><b>呼吸 ${15+s[0]*4} 回/分</b></div><p>血液が酸素を運ぶ速さも上がります。</p>`},
    environment:{title:"生態系のつながり",hint:"草食動物を増やすと、他の生物はどうなる？",controls:[['植物',1,10,1,6,''],['草食動物',1,10,1,3,''],['肉食動物',0,8,1,2,'']],draw:s=>{const p=s[0],h=s[1],c=s[2];return `<div class="food-chain"><span>🌿 ${p}</span><i>→</i><span>🐇 ${h}</span><i>→</i><span>🦊 ${c}</span></div><div class="eco-bars"><span style="height:${p*8}px"></span><span style="height:${h*8}px"></span><span style="height:${c*8}px"></span></div><p>${h>p?'植物が足りず、減少しそうです。':'食べる・食べられる関係がつながっています。'}</p>`}},
    earth:{title:"地層のでき方",hint:"水の流れを変えると、どの粒が先に積もる？",controls:[['水の速さ',0,100,1,55,'%'],['火山灰',0,1,1,0,'']],draw:s=>`<div class="earth-cut"><span style="height:${20+s[0]/5}px;background:#c49a6c"></span><span style="height:${15+(100-s[0])/6}px;background:#e2c18e"></span><span style="height:${25+s[1]*18}px;background:#756653"></span></div><p>${s[1]?'火山灰の層が目印になりました。':'流れが弱いほど、細かな粒も積もります。'}</p>`}
  };
  function mount(root,{manifest}){const cfg=CONFIG[manifest.id], s=cfg.controls.map(x=>x[4]); let timer;
    root.innerHTML=`<nav class="breadcrumbs"><button class="text-button" type="button" data-lab-home>LAB一覧</button><span>›</span><span>${esc(manifest.title)}</span></nav><section class="science-lab extra-only" style="--lab-accent:${manifest.accent}"><header class="lab-titlebar"><div><p class="eyebrow">${esc(manifest.unit)}</p><h1>${manifest.icon} ${esc(manifest.title)}</h1><p>${esc(manifest.summary)}</p></div></header><div class="lab-workspace"><section class="simulation-column"><div class="sim-stage extra-stage"></div><div class="sim-readout extra-readout"></div><div class="sim-actions"><button class="secondary-button" data-sim-reset type="button">リセット</button><button class="secondary-button" data-sim-step type="button">変化を進める</button></div></section><aside class="control-panel"></aside></div><p class="model-note"><b>モデルについて：</b>学習する関係が見えやすいよう、現実の大きさや時間を縮めています。</p><div class="lab-guide"><span>🔎</span><p>${esc(cfg.hint)}</p></div></section>`;
    const stage=root.querySelector('.extra-stage'), read=root.querySelector('.extra-readout'), panel=root.querySelector('.control-panel');
    function render(){stage.innerHTML=cfg.draw(s); read.textContent='条件を動かすと、すぐに変化します。'; panel.innerHTML='<div class="control-heading"><p class="eyebrow">CONTROL</p><h2>条件を変える</h2></div>'+cfg.controls.map((c,i)=>`<label class="range-control"><span>${c[0]} <output>${s[i]}${c[5]}</output></span><input data-i="${i}" type="range" min="${c[1]}" max="${c[2]}" step="${c[3]}" value="${s[i]}"></label>`).join(''); panel.querySelectorAll('input').forEach(el=>el.addEventListener('input',()=>{s[+el.dataset.i]=+el.value; render()}));}
    render(); root.addEventListener('click',e=>{if(e.target.matches('[data-sim-reset]')){cfg.controls.forEach((c,i)=>s[i]=c[4]);render()} if(e.target.matches('[data-sim-step]')){s[0]=clamp(s[0]+(cfg.controls[0][2]-cfg.controls[0][1])/5,cfg.controls[0][1],cfg.controls[0][2]);render()}}); return()=>clearTimeout(timer);
  }
  Object.keys(CONFIG).forEach(id=>window.RikaLabSimulations[id]={mount});
})();
