(() => { "use strict";
  const K="rikaLab6.plants.v1", esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const fresh=()=>({water:70,light:80,leaves:5,covered:0,inside:false,waterView:false,leafView:false,trace:0,time:0,records:[],evidence:[]});
  const load=()=>{try{return {...fresh(),...JSON.parse(localStorage.getItem(K))};}catch(_){return fresh();}};
  const save=s=>{try{localStorage.setItem(K,JSON.stringify(s));}catch(_){}};
  function mount(root){let s=load(),raf=0,run=false;
    root.innerHTML=`<nav class="breadcrumbs"><button class="text-button" type="button" data-lab-home>LAB一覧</button><span>›</span><span>植物LAB</span></nav><section class="plants-lab"><header class="lab-titlebar"><div><p class="eyebrow">植物の養分と水</p><h1>🌿 植物LAB</h1><p>水を与え、条件を変え、時間を進めて植物のはたらきを調べよう。</p></div><div class="plant-status" data-status></div></header><div class="plants-workspace"><section class="plant-stage-wrap"><svg class="plant-svg" viewBox="0 0 760 560" data-svg></svg><div class="plant-tip">通常は外からの観察。必要なときだけ「中を見る」をONにします。</div></section><aside class="plants-panel" data-panel></aside></div><section class="plant-bottom"><div class="plant-record"><h2>実験記録</h2><label>予想<textarea data-prediction placeholder="どうなると思う？"></textarea></label><label>考察<textarea data-thought placeholder="見えたことと考えたことを書こう"></textarea></label><button class="primary-button" data-record type="button">証拠カードに保存</button><button class="secondary-button" data-clear type="button">結果をリセット</button></div><div class="plant-data"><h2>水量の変化</h2><div data-graph></div><div data-evidence></div></div></section><p class="model-note">青い通り道・粒・葉から出るミストは、見えない現象を考えるためのモデルです。実際の植物を透視した映像ではありません。</p></section>`;
    const svg=root.querySelector('[data-svg]'),panel=root.querySelector('[data-panel]');
    function draw(){const loss=Math.min(55,s.time*(.12+s.leaves*.035)*(s.light/100)), remaining=Math.max(0,s.water-loss);const reached=Math.min(1,s.time/18);const starch=Math.max(0,Math.round((s.light/100)*(s.leaves/5)*(1-s.covered/100)*100));
      const leaves=Array.from({length:s.leaves},(_,i)=>`<g class="plant-leaf ${s.covered&&i%2===0?'covered-leaf':''}" data-leaf="${i}"><ellipse cx="${360+(i%2?1:-1)*(58+i*18)}" cy="${155+i*38}" rx="58" ry="22" transform="rotate(${i%2?22:-22} ${360+(i%2?1:-1)*(58+i*18)} ${155+i*38})"/></g>`).join("");
      svg.innerHTML=`<rect width="760" height="560" fill="#edf6ef"/><text x="28" y="38" class="plant-board-title">PLANT OBSERVATION</text><path d="M360 365V105M360 365Q300 425 230 455M360 365Q420 425 495 455" stroke="#895e42" stroke-width="24" fill="none" stroke-linecap="round"/><path d="M360 365V105M360 365Q300 425 230 455M360 365Q420 425 495 455" stroke="#53a9b8" stroke-width="${s.inside?8:0}" fill="none" stroke-linecap="round"/>${leaves}${s.waterView?Array.from({length:12},(_,i)=>`<circle class="plant-water-dot" cx="360" cy="${350-(i*22)%250}" r="5" style="--delay:${i*.12}s"/>`).join(""):''}${s.leafView?Array.from({length:Math.max(2,s.leaves)},(_,i)=>`<circle class="plant-mist" cx="${350+(i%2?1:-1)*60}" cy="${145+i*38}" r="6"/>`).join(""):''}<rect x="285" y="450" width="150" height="48" rx="12" fill="#b98256"/><text x="360" y="480" text-anchor="middle" class="plant-label">土と根</text><text x="380" y="535" class="plant-caption">時間 ${Math.round(s.time)}　残りの水 ${Math.round(remaining)}</text>`;
      panel.innerHTML=`<h2>条件と観察</h2><p>触った条件の変化をすぐに比べてみよう。</p><section class="plant-controls"><label>水の量 <output>${s.water}</output><input data-k="water" type="range" min="0" max="100" value="${s.water}"></label><label>光 <output>${s.light}%</output><input data-k="light" type="range" min="0" max="100" value="${s.light}"></label><label>葉の枚数 <output>${s.leaves}枚</output><input data-k="leaves" type="range" min="0" max="6" value="${s.leaves}"></label><label>おおう葉 <output>${s.covered}%</output><input data-k="covered" type="range" min="0" max="100" value="${s.covered}"></label></section><div class="plant-buttons"><button data-water>💧 水を与える</button><button data-trace>${s.waterView?'水の動きを隠す':'水の動きを見る'}</button><button data-inside>${s.inside?'外から見る':'中を見る'}</button><button data-leaf>${s.leafView?'葉のまわりを隠す':'葉のまわりを見る'}</button></div><div class="plant-time"><button data-step>▶ ×1</button><button data-fast>▶▶ ×10</button><button data-run>${run?'⏸ 止める':'▶ 自動で進める'}</button><button data-reset>リセット</button></div><div class="plant-readout"><b>観察</b><span>${s.time<4?'まず水を与えて時間を進めよう':s.light>50?'葉に光が当たっている':'光の条件を変えて比べよう'}</span><small>でんぷんモデルの目安 ${starch}%（結論ではなく比較用）</small></div>`;
      root.querySelector('[data-status]').textContent=s.time?`時間 ${Math.round(s.time)}：条件を比べています`:'植物を観察して、まず水を与えよう';
      root.querySelector('[data-graph]').innerHTML=`<div class="plant-bars"><div><span>開始時</span><i style="width:100%"></i></div><div><span>現在</span><i style="width:${remaining}%"></i></div></div><p class="plant-observation">水量 ${Math.round(remaining)}。変化したことを観察カードにできます。</p>`;
      root.querySelector('[data-evidence]').innerHTML=s.evidence.length?`<div class="plant-evidence-list">${s.evidence.slice(0,5).map((e,i)=>`<article><b>証拠${i+1}</b><span>${esc(e)}</span></article>`).join('')}</div>`:'';
      bind();
    }
    function bind(){panel.querySelectorAll('input').forEach(x=>x.oninput=()=>{s[x.dataset.k]=+x.value;draw();});panel.querySelector('[data-water]').onclick=()=>{s.water=Math.min(100,s.water+20);draw();};panel.querySelector('[data-trace]').onclick=()=>{s.waterView=!s.waterView;draw();};panel.querySelector('[data-inside]').onclick=()=>{s.inside=!s.inside;draw();};panel.querySelector('[data-leaf]').onclick=()=>{s.leafView=!s.leafView;draw();};panel.querySelector('[data-step]').onclick=()=>{s.time+=1;draw();};panel.querySelector('[data-fast]').onclick=()=>{s.time+=10;draw();};panel.querySelector('[data-run]').onclick=()=>{run=!run;if(run)loop();draw();};panel.querySelector('[data-reset]').onclick=()=>{Object.assign(s,fresh(),{records:s.records,evidence:s.evidence});run=false;draw();};}
    function loop(){if(!run)return;s.time+=.15;draw();raf=requestAnimationFrame(loop);}
    root.querySelector('[data-record]').onclick=()=>{const e=`時間${Math.round(s.time)}・水${s.water}・光${s.light}%・葉${s.leaves}枚・水量の変化${Math.round(Math.max(0,s.water-s.time*(.12+s.leaves*.035)*(s.light/100)))}`;s.evidence.unshift(e);s.records.unshift({e,prediction:root.querySelector('[data-prediction]').value,thought:root.querySelector('[data-thought]').value});save(s);draw();};root.querySelector('[data-clear]').onclick=()=>{s.evidence=[];s.records=[];save(s);draw();};draw();return()=>{run=false;cancelAnimationFrame(raf);};
  } window.RikaLabSimulations=window.RikaLabSimulations||{};window.RikaLabSimulations.plants={mount};
})();
